In [14]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [15]:
#Creating a Numpy Array

lst = [1,2,3,4]

arr = np.array(lst)
print(arr)

[1 2 3 4]


In [16]:
# .dtype
print(arr.dtype)

int32


In [18]:
from sys import getsizeof

lst = []
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

56
104


In [23]:
#Operations with Numpy Arrays

prices = [30, 25, 40, 20, 20, 35 ,50, 35]

#with list
new_prices = [price-5 for price in prices]
print(new_prices)

#with numpy
prices_arr = np.array(prices)
prices_arr = prices_arr -5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [41]:
#practice_test_grade
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 5
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[:, 4])

[92 90 77 95 97]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [52]:
#Logical Operations

#masking
a = np.array([1,2,3,4,5,6])
mask = a > 3
print(mask)

#selection
selected = a[a > 3]
print(selected)

#combined
selected = a[(a > 4) | (a < 2)]
print(selected)

selected = a[(a < 4) & (a < 2)]
print(selected)

[False False False  True  True  True]
[4 5 6]
[1 5 6]
[1]


In [58]:
#Practice

porridge = np.array([79, 65 , 50 , 63, 56, 90, 85, 98, 79, 51])
print(porridge)

cold = porridge[porridge < 60]
print(cold)

hot = porridge[porridge > 80]
print(hot)

just_right = porridge[(porridge > 60 ) & (porridge < 80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
