In [2]:
#Random number generator
import numpy as np

np.random.seed(0)
arr1 = np.random.randint(10, size=6)
print(arr1)

arr2 = np.random.randint(10, size=(3,4))
print(arr2)

arr3 = np.random.randint(10, size=(3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [3]:
#Attributes
print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape) #**
print("arr2.size = ", arr2.size) #**
print("arr2.dtype = ", arr2.dtype) #**
print("arr2.itemsize = ", arr2.itemsize)
print("arr2.nbytes = ", arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [4]:
#Slicing

arr= np.arange(10)
print(arr)



[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Multi-dimensional 
np.random.seed(0)
arr = np.random.randint(10, size=(6,8))
print(arr)

arr_sub = arr[3:5, 4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [8]:
#.copy()

arr = np.array([12,5,2,4, [7,6,8,8,]])

<ipython-input-8-b1785515a06b>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([12,5,2,4, [7,6,8,8,]])
