In [23]:
import pandas as pd
import numpy as np

In [24]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

print(np.concatenate([x,y,z]))

print(np.vstack([x,y,z]))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
ser1 = pd.Series(['A', 'B', 'C'], index = [1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4,5,6])
print(pd.concat([ser1, ser2]))

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [27]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC', [1, 2])

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [28]:
df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])

print(df1)
print(df2)

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4


In [42]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])

print(df3)
print(df4)

print(pd.concat([df3, df4], axis=1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [51]:
pd.concat([x,y], verify_integrity=True)

except ValueError as e:

SyntaxError: invalid syntax (<ipython-input-51-683f7d3b3877>, line 3)

In [31]:
print(pd.concat([x,y], ignore_index = True))

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [50]:
print(pd.concat([x, y], join='outer')) #합집합
print(pd.concat([x, y], join='inner')) #교집합

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid